name: Build 11ty
on:
  push:
    branches:    
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npm run build

      - name: Archive site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site